version: 2.1

jobs:
  build:
    docker:
      - image: 45635463452425452/cdk-mage:0.5
    resource_class: small
    working_directory: ~/dev/wowmate
    steps:
      - checkout

      # GO

      - restore_cache:
          keys: 
            - go_pkg_{{ checksum "services/api/damage-boss-fight-uuid/go.sum" }}-{{ checksum "services/api/damage-encounter-id/go.sum" }}-{{ checksum "services/golib/go.sum" }}-{{ checksum "services/upload/athena/go.sum" }}-{{ checksum "services/upload/check/go.sum" }}-{{ checksum "services/upload/import/go.sum" }}-{{ checksum "services/upload/parquet/go.sum" }}-{{ checksum "services/upload/partitions/go.sum" }}-{{ checksum "services/upload/size/go.sum" }}-{{ checksum "services/upload/athena-repair/go.sum" }}


      - run:  mage go
      - run:  du -hcs ~/.cache/go-build

      - save_cache:
          key: go_pkg_{{ checksum "services/api/damage-boss-fight-uuid/go.sum" }}-{{ checksum "services/api/damage-encounter-id/go.sum" }}-{{ checksum "services/golib/go.sum" }}-{{ checksum "services/upload/athena/go.sum" }}-{{ checksum "services/upload/check/go.sum" }}-{{ checksum "services/upload/import/go.sum" }}-{{ checksum "services/upload/parquet/go.sum" }}-{{ checksum "services/upload/partitions/go.sum" }}-{{ checksum "services/upload/size/go.sum" }}-{{ checksum "services/upload/athena-repair/go.sum" }}
          paths: 
            - /go/pkg
            - /root/.cache/go-build 

      # FRONTEND

      - restore_cache:
          keys: 
            - frontend_yarn-{{ checksum "services/frontend/yarn.lock" }}

      - run: mage frontend

      - save_cache:
          key: frontend_yarn-{{ checksum "services/frontend/yarn.lock" }}
          paths: 
            -  services/frontend/node_modules

      # CDK

      - restore_cache:
          keys: 
            - cdk_out

      - restore_cache:
          keys: 
            - cdk_npm-{{ checksum "package-lock.json" }}

      - run: mage deploy
      # the asset.* directories don't need to be cached. but we do need to cache the other files
      # to "remember" the state, so not every lambda has to be deployed every time a change is made
      - run: rm -rf cdk.out/asset.*

      - save_cache:
          key: cdk_out{{ epoch }}
          paths: 
            -  cdk.out

      - save_cache:
          key: cdk_npm-{{ checksum "package-lock.json" }}
          paths: 
            -  node_modules
      # - attach_workspace: 
      #     at: ~/wowmate
      # - run: 
      #     name: go
      #     command: |
      #       mage go


workflows:
  version: 2
  wowmatecicd:
    jobs:
      - build