version: 2.1

jobs:
  build:
    docker:
      - image: 45635463452425452/cdk-mage:0.3
    resource_class: small
    working_directory: ~/dev/wowmate
    steps:
      - checkout
      - restore_cache:
          keys: 
            - cdk.out-{{ checksum "cdk.out/tree.json" }}
            - cdk.out
      - run:
          name: build go
          command: |
            mage go
      - run:
          name: build frontend
          command: |
            mage frontend
      - run:
          name: deploy
          command: |
            mage deploy
      - save_cache:
          key: cdk.out-{{ checksum "cdk.out/tree.json" }}
          paths: 
            -  cdk.out
      # - attach_workspace: 
      #     at: ~/wowmate

workflows:
  version: 2
  wowmatecicd:
    jobs:
      - build