version: 2.1
jobs:
  build:
    docker:
      - image: node:13
    resource_class: small
    working_directory: ~/wowmate
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}
      - run: 
          name: Install npm 
          working_directory: ~/wowmate/services/frontend
          command: | 
            ls -l 
            pwd 
            npm install
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths: 
            -  ./node_modules
      # TODO: add main.js content
      - run: 
          name: Build npm
          working_directory: ~/wowmate/services/frontend
          command: | 
            ls -l 
            pwd
            npm run build
      - persist_to_workspace:
          root: .
          paths: 
            - dist
  deploy:
    docker:
      - image: circleci/node:latest
    resource_class: small
    working_directory: ~/wowmate
    steps:
      - checkout
      - run: 
          name: Deploy to AWS
          working_directory: ~/wowmate/services/frontend
          command: ls 

workflows:
  version: 2
  work_flow_name:
    jobs:
      - build
      - deploy:
          requires:
            - build