version: 2.1

jobs:
  build:
    docker:
      - image: 45635463452425452/cdk-mage:0.3
    resource_class: small
    working_directory: ~/dev/wowmate
    steps:
      - checkout
      - restore_cache:
          key: cdk.out-{{ checksum "cdk.out/tree.json" }}
          key: cdk.out
      - run:
          name: build and deploy
          command: |
            ls
            mage build
            mage deploy
            ls
      - save_cache:
          key: cdk.out-{{ checksum "cdk.out/tree.json" }}
          paths: 
            -  cdk.out
      # - attach_workspace: 
      #     at: ~/wowmate

workflows:
  version: 2
  wowmatecicd:
    jobs:
      - build