version: 2.1
jobs:
  build:
    docker:
      - image: node:13
    resource_class: small
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: 
          command: |
            cd services/frontend
            npm install
            npm run build

  # test:
  #   docker:
  #     - image: circleci/node:latest
  #   resource_class: small
  #   working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  #   steps:
  #     - checkout
  #     - run: ls

# workflows:
#   version: 2
#   work_flow_name:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build