version: 2.1
jobs:
  build:
    docker:
      - image: node:13
    resource_class: small
    working_directory: ~/wowmate
    steps:
      - checkout
      - attach_workspace: 
          at: ~/wowmate
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}
      - run: 
          name: Install npm 
          working_directory: ~/wowmate/services/frontend
          command: | 
            ls -l 
            pwd 
            npm install
            # TODO: only run install when no cache was found
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths: 
            -  ./node_modules
      # TODO: add main.js content
      - run: 
          name: Build npm
          working_directory: ~/wowmate/services/frontend
          command: | 
            pwd
            npm run build
            ls -l 
      - persist_to_workspace:
          root: .
          paths: 
            - services/frontend/dist
      # - run: 
      #     name: Check tmp
      #     command: | 
      #       ls /tmp
  deploy:
    docker:
      - image: circleci/node:latest
    resource_class: small
    working_directory: ~/wowmate
    steps:
      # - checkout
      - attach_workspace: 
          at: ~/wowmate
      - run: 
          name: Deploy to AWS
          working_directory: ~/wowmate/services/frontend
          command: ls dist

workflows:
  version: 2
  wowmatecicd:
    jobs:
      - build
      - deploy:
          requires:
            - build