version: 2.1
jobs:
  build:
    docker:
      - image: node:13
    resource_class: small
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/services/frontend
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths: 
            -  ./node_modules

      - run: ls -l

  # test:
  #   docker:
  #     - image: circleci/node:latest
  #   resource_class: small
  #   working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  #   steps:
  #     - checkout
  #     - run: ls

# workflows:
#   version: 2
#   work_flow_name:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build