version: 2.1
jobs:
  build:
    docker:
      - image: node:13
    resource_class: small
    working_directory: ~/wowmate
    steps:
      - checkout
      # - restore_cache:
      #     key: v1-npm-{{ checksum "services/frontend/package-lock.json" }}
      - run: 
          name: Install npm 
          command: | 
            ls -l 
            pwd 
          # npm install
      # - save_cache:
      #     key: v1-npm-{{ checksum "services/frontend/package-lock.json" }}
      #     paths: 
      #       -  ./node_modules

            # TODO: add main.js content

      - run: 
          name: Build npm
          working_directory: ~/wowmate/services/frontend
          command: | 
            ls -l 
            pwd
          # npm run build

  # test:
  #   docker:
  #     - image: circleci/node:latest
  #   resource_class: small
  #   working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  #   steps:
  #     - checkout
  #     - run: ls

# workflows:
#   version: 2
#   work_flow_name:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build