version: 2.1
jobs:
  build_infrastructure:
    docker:
      - image: node:13
    resource_class: small
    working_directory: ~/wowmate
    steps:
      - checkout
      - attach_workspace: 
          at: ~/wowmate
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: 
          name: Install npm 
          command: | 
            if [ ! -d node_modules ]; then
              echo npm install
              npm install
            else
              echo skip install because the node_modules are cached
            fi
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths: 
            -  node_modules
      - run: 
          name: Build npm
          command: | 
            pwd
            ls -l 
          # note need all other stages to finish first
          # npm install -g typescript
          # npm i -g aws-cdk
          # cdk synth
          # ls -l
      # - persist_to_workspace:
      #     root: .
      #     paths: 
      #       - cdk.out
  deploy_to_aws:
    docker:
      - image: circleci/node:latest
    resource_class: small
    working_directory: ~/wowmate
    steps:
      - attach_workspace: 
          at: ~/wowmate
      - run: 
          name: Deploy to AWS
          command: ls 

workflows:
  version: 2
  wowmatecicd:
    jobs:
      - build_infrastructure
      - deploy_to_aws:
          requires:
            - build_infrastructure