version: 2.1

jobs:
  build:
    docker:
      - image: 45635463452425452/cdk-mage:0.3
    resource_class: small
    working_directory: ~/dev/wowmate
    steps:
      - checkout

      - run: mage go

      - run: mage frontend

      - restore_cache:
          keys: 
            - cdk.out-{{ checksum "cdk.out/tree.json" }}
            - cdk.out

      - restore_cache:
          keys: 
            - cdk.npm-{{ checksum "package-lock.json" }}
            - cdk.npm

      - run: mage deploy

      - save_cache:
          key: cdk.out-{{ checksum "cdk.out/tree.json" }}
          paths: 
            -  cdk.out

      - save_cache:
          key: cdk.npm-{{ checksum "package-lock.json" }}
          paths: 
            -  node_modules
      # - attach_workspace: 
      #     at: ~/wowmate

workflows:
  version: 2
  wowmatecicd:
    jobs:
      - build