name: CI/CD

on:
  pull_request:
    branches: [ prod ]
  push:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'

      # BUILD CACHES
      # if no go file changes the binaries are cached and don't have to be rebuild
      - name: Cache go builds
        uses: actions/cache@v2
        id: go-build-cache
        with:
          path: dist
          key: go-build-${{ hashFiles('services/**/*.go') }}-${{ hashFiles('services/**/go.sum') }}

      # INSTALL CACHES
      # caches all go dependencies
      # can't not get cache if the go build did not change
      - name: Cache go deps
        uses: actions/cache@v2
        id: go-cache
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-

      # caches node_modules of presign lambda
      - name: Cache presign npm
        uses: actions/cache@v2
        id: presign-cache
        with:
          path: services/upload/presign/node_modules
          key: presign-${{ hashFiles('services/upload/package-lock.json') }}
          restore-keys: presign-

      - name: Cache cdk npm dependencies
        uses: actions/cache@v2
        id: cdk-cache
        with:
          path: node_modules
          key: cdk-${{ hashFiles('package-lock.json') }}

      # INSTALL:
      - name: Install CDK
        if: steps.cdk-cache.outputs.cache-hit != 'true'
        run: ./wm.sh install cdk

      - name: Install go
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: ./wm.sh install go

      - name: Install presign
        if: steps.presign-cache.outputs.cache-hit != 'true'
        run: ./wm.sh install presign

      # BUILD:
      # GO
      - name: Build go
        if: steps.go-build-cache.outputs.cache-hit != 'true'
        run: ./wm.sh build go

  setup-frontend-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15.x

      # BUILD CACHES
      # if no js or vue file changes the services/frontend/dist dir is cached
      - name: Cache frontend build
        uses: actions/cache@v2
        id: frontend-build-cache
        with:
          path: services/frontend/dist
          key: frontend-build-${{ hashFiles('services/frontend/**/*.vue') }}-${{ hashFiles('services/frontend/**/*.js') }}-${{ hashFiles('services/upload/package-lock.json') }}

      # INSTALL CACHES
      # cache dependencies for nuxt frontend
      - name: Cache frontend yarn
        uses: actions/cache@v2
        id: frontend-cache
        with:
          path: services/frontend/node_modules
          key: frontend-${{ hashFiles('services/frontend/yarn.lock') }}
          restore-keys: |
            frontend-

      # INSTALL:
      - name: Install frontend
        if: steps.frontend-cache.outputs.cache-hit != 'true'
        run: ./wm.sh install frontend

      # BUILD:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-branch

      # FRONTEND
      - name: Build frontend
        env:
          NUXT_ENV: dev
        if: steps.frontend-build-cache.outputs.cache-hit != 'true'
        run: ./wm.sh build frontend

  setup-frontend-preprod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15.x

      # BUILD CACHES
      # if no js or vue file changes the services/frontend/dist dir is cached
      - name: Cache frontend build
        uses: actions/cache@v2
        id: frontend-build-preprod-cache
        with:
          path: services/frontend/dist
          key: frontend-build-preprod${{ hashFiles('services/frontend/**/*.vue') }}-${{ hashFiles('services/frontend/**/*.js') }}-${{ hashFiles('services/upload/package-lock.json') }}

      # INSTALL CACHES
      # cache dependencies for nuxt frontend
      - name: Cache frontend yarn
        uses: actions/cache@v2
        id: frontend-cache
        with:
          path: services/frontend/node_modules
          key: frontend-${{ hashFiles('services/frontend/yarn.lock') }}

      # INSTALL:
      - name: Install frontend
        if: steps.frontend-cache.outputs.cache-hit != 'true'
        run: ./wm.sh install frontend

      # BUILD:
      # FRONTEND
      - name: Build frontend
        env:
          NUXT_ENV: preprod
        run: ./wm.sh build frontend

  setup-frontend-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15.x

      # BUILD CACHES
      # if no js or vue file changes the services/frontend/dist dir is cached
      - name: Cache frontend build
        uses: actions/cache@v2
        id: frontend-build-prod-cache
        with:
          path: services/frontend/dist
          key: frontend-build-prod${{ hashFiles('services/frontend/**/*.vue') }}-${{ hashFiles('services/frontend/**/*.js') }}-${{ hashFiles('services/upload/package-lock.json') }}

      # INSTALL CACHES
      # cache dependencies for nuxt frontend
      - name: Cache frontend yarn
        uses: actions/cache@v2
        id: frontend-cache
        with:
          path: services/frontend/node_modules
          key: frontend-${{ hashFiles('services/frontend/yarn.lock') }}

      # INSTALL:
      - name: Install frontend
        if: steps.frontend-cache.outputs.cache-hit != 'true'
        run: ./wm.sh install frontend

      # BUILD:
      # FRONTEND
      - name: Build frontend
#        env:
#          NUXT_ENV: prod
#         no env var defaults to api.wowmate.io
        run: ./wm.sh build frontend

  cfn-nag:
    runs-on: ubuntu-latest
    needs:
      - setup-go
      - setup-frontend-dev
    steps:
        # composite actions (https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action)
        # can only execute run steps and not uses, which means I can't DRY up the setup steps
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Cache CDK npm
        uses: actions/cache@v2
        id: cdk-cache
        with:
          path: node_modules
          key: cdk-${{ hashFiles('package-lock.json') }}

      - name: Cache go builds
        uses: actions/cache@v2
        id: go-build-cache
        with:
          path: dist
          key: go-build-${{ hashFiles('services/**/*.go') }}-${{ hashFiles('services/**/go.sum') }}

      - name: Cache frontend build
        uses: actions/cache@v2
        id: frontend-build-cache
        with:
          path: services/frontend/dist
          key: frontend-build-${{ hashFiles('services/frontend/**/*.vue') }}-${{ hashFiles('services/frontend/**/*.js') }}-${{ hashFiles('services/upload/package-lock.json') }}

      - name: Compile CDK typescript
        run: ./wm.sh build cdk

      - name: Synthezise CDK to CFN
        run: ./wm.sh synth

      - name: Check cfn bestpractices with cfn_nag for prod
        uses: stelligent/cfn_nag@master
        with:
          input_path: cdk.out/wm.template.json
          extra_args: |
            --print-suppression
            --blacklist-path misc/cfn-nag-blacklist.yml
            --fail-on-warnings

  deploy-dev:
    runs-on: ubuntu-latest
    needs:
      - setup-go
      - setup-frontend-dev
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Cache CDK npm dependencies
        uses: actions/cache@v2
        id: cdk-cache
        with:
          path: node_modules
          key: cdk-${{ hashFiles('package-lock.json') }}

      - name: Cache go builds
        uses: actions/cache@v2
        id: go-build-cache
        with:
          path: dist
          key: go-build-${{ hashFiles('services/**/*.go') }}-${{ hashFiles('services/**/go.sum') }}

      - name: Cache presign npm
        uses: actions/cache@v2
        id: presign-cache
        with:
          path: services/upload/presign/node_modules
          key: presign-${{ hashFiles('services/upload/package-lock.json') }}

      - name: Cache frontend build
        uses: actions/cache@v2
        id: frontend-build-cache
        with:
          path: services/frontend/dist
          key: frontend-build-${{ hashFiles('services/frontend/**/*.vue') }}-${{ hashFiles('services/frontend/**/*.js') }}-${{ hashFiles('services/upload/package-lock.json') }}

      - name: Fix file permissions # files are zipped during uploading to the artifact store, which loses the file permission
        run: chmod -R 755 dist

      - name: Compile CDK typescript
        run: ./wm.sh build cdk

      - name: Configure AWS dev credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to dev
        env:
          CDK_STACK: ${{ steps.cdk-stack.outputs.stack }}
        run: ./wm.sh deploy dev

  cdk-diff:
    runs-on: ubuntu-latest
    needs:
      - setup-go
      - setup-frontend-dev
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Cache cdk npm dependencies
        uses: actions/cache@v2
        id: cdk-cache
        with:
          path: node_modules
          key: cdk-${{ hashFiles('package-lock.json') }}

      - name: Cache go builds
        uses: actions/cache@v2
        id: go-build-cache
        with:
          path: dist
          key: go-build-${{ hashFiles('services/**/*.go') }}-${{ hashFiles('services/**/go.sum') }}

      - name: Cache frontend build
        uses: actions/cache@v2
        id: frontend-build-cache
        with:
          path: services/frontend/dist
          key: frontend-build-${{ hashFiles('services/frontend/**/*.vue') }}-${{ hashFiles('services/frontend/**/*.js') }}-${{ hashFiles('services/upload/package-lock.json') }}

      - name: Compile CDK typescript
        run: ./wm.sh build cdk

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-branch

      - name: Configure AWS prod credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Post CDK Diff as comment to PR
        if: steps.extract-branch.outputs.branch != 'prod'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: ./wm.sh diff prod


#  analyze:
#    name: Analyze
#    runs-on: ubuntu-latest
#
#    strategy:
#      fail-fast: false
#      matrix:
#        language: [ 'go' ]
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Initialize CodeQL
#        uses: github/codeql-action/init@v1
#        with:
#          languages: ${{ matrix.language }}
#
#      - name: Autobuild
#        uses: github/codeql-action/autobuild@v1
#
#      - name: Perform CodeQL Analysis
#        uses: github/codeql-action/analyze@v1

  go-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS dev credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'

      - name: Cache go deps
        uses: actions/cache@v2
        id: go-cache
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-

      - name: Lint Golang
        run: ./wm.sh lint go

  deploy-preprod:
    runs-on: ubuntu-latest
    needs:
      - setup-frontend-preprod
      - setup-go
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Cache CDK npm dependencies
        uses: actions/cache@v2
        id: cdk-cache
        with:
          path: node_modules
          key: cdk-${{ hashFiles('package-lock.json') }}

      - name: Cache go builds
        uses: actions/cache@v2
        id: go-build-cache
        with:
          path: dist
          key: go-build-${{ hashFiles('services/**/*.go') }}-${{ hashFiles('services/**/go.sum') }}

      - name: Cache presign npm
        uses: actions/cache@v2
        id: presign-cache
        with:
          path: services/upload/presign/node_modules
          key: presign-${{ hashFiles('services/upload/package-lock.json') }}

      - name: Cache frontend build
        uses: actions/cache@v2
        id: frontend-build-preprod-cache
        with:
          path: services/frontend/dist
          key: frontend-build-preprod${{ hashFiles('services/frontend/**/*.vue') }}-${{ hashFiles('services/frontend/**/*.js') }}-${{ hashFiles('services/upload/package-lock.json') }}

      - name: Fix file permissions
        run: chmod -R 755 dist

      - name: Compile CDK typescript
        run: ./wm.sh build cdk

      - name: Configure AWS preprod credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to preprod
        run: ./wm.sh deploy preprod

  cypress:
    runs-on: ubuntu-latest
    needs: deploy-preprod
    steps:
      - uses: actions/checkout@v2

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: services/frontend
          config: baseUrl=https://preprod.wowmate.io

  lighthouse-landingpage:
    runs-on: ubuntu-latest
    needs: deploy-preprod
    steps:
      - uses: actions/checkout@v2

      - name: Audit Preprod Landingpgage
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: https://preprod.wowmate.io/
          budgetPath: ./misc/budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          configPath: misc/.lighthouserc.json

  lighthouse-mythicplus:
    runs-on: ubuntu-latest
    needs: deploy-preprod
    steps:
      - uses: actions/checkout@v2

      - name: Audit Mythicplus page
        if: steps.extract-branch.outputs.branch != 'prod'
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: https://preprod.wowmate.io/mythicplus
          budgetPath: ./misc/budget-mythicplus.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          configPath: misc/.lighthouserc.json

  api-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-preprod
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'

      - name: Configure AWS dev credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run API tests
        run: |
          cd services/test/api-test
          go run .

  lambda-integration-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-preprod
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'

      - name: Configure AWS dev credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run convert integration test
        run: |
          cd services/test/upload-integration-test
          go run .

  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - lighthouse-landingpage
      - lighthouse-mythicplus
      - lambda-integration-tests
      - api-tests
      - setup-frontend-prod
      - go-lint
      - cfn-nag
      - cdk-diff
      - deploy-dev
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Cache go builds
        uses: actions/cache@v2
        id: go-build-cache
        with:
          path: dist
          key: go-build-${{ hashFiles('services/**/*.go') }}-${{ hashFiles('services/**/go.sum') }}

      - name: Cache presign npm
        uses: actions/cache@v2
        id: presign-cache
        with:
          path: services/upload/presign/node_modules
          key: presign-${{ hashFiles('services/upload/package-lock.json') }}

      - name: Cache frontend build
        uses: actions/cache@v2
        id: frontend-build-prod-cache
        with:
          path: services/frontend/dist
          key: frontend-build-prod${{ hashFiles('services/frontend/**/*.vue') }}-${{ hashFiles('services/frontend/**/*.js') }}-${{ hashFiles('services/upload/package-lock.json') }}

      - name: Cache CDK npm dependencies
        uses: actions/cache@v2
        id: cdk-cache
        with:
          path: node_modules
          key: cdk-${{ hashFiles('package-lock.json') }}

      - name: Fix file permissions
        run: chmod -R 755 dist

      - name: Compile CDK typescript
        run: ./wm.sh build cdk

      - name: Configure AWS prod credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-branch

      - name: Deploy to prod
        if: steps.extract-branch.outputs.branch == 'prod'
        run: ./wm.sh deploy prod
